using DavxeShop.Library.Services.Interfaces;
using DavxeShop.Models.dbModels;
using DavxeShop.Models.Request.User;
using DavxeShop.Models.Response;
using DavxeShop.Persistance.Interfaces;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace DavxeShop.Library.Services
{
    public class UserService : IUserService
    {
        private readonly IDavxeShopDboHelper _davxeShopDboHelper;
        private readonly IEmailService _emailService;
        private readonly string _secretKey;

        public UserService(IDavxeShopDboHelper davxeShopDboHelper, IConfiguration configuration, IEmailService emailService)
        {
            _davxeShopDboHelper = davxeShopDboHelper;
            _secretKey = configuration["AppSettings:SecretKey"] ?? throw new ArgumentNullException(nameof(configuration), "No se ha encontrado la SecretKet en la configuracion.");
            _emailService = emailService;
        }

        public List<User> GetUsers()
        {
            return _davxeShopDboHelper.GetUsers();
        }

        public UserBasicDto GetUser(int UserId)
        {
            return _davxeShopDboHelper.GetUser(UserId);
        }

        public User RequestHashed(RegisterRequest request)
        {
            var requestHashed = new User
            {
                DNI = request.DNI,
                Name = request.Name,
                Email = request.Email,
                BirthDate = request.BirthDate,
                City = request.City,
                Password = BCrypt.Net.BCrypt.HashPassword(request.Password, BCrypt.Net.BCrypt.GenerateSalt(5)),
                RolId = 2,
                ImageBase64 = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCALgAuADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDqaKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoopyI8rbY0LN6KCT+lADaK04PD+pz4ItWQeshA/nzWhF4Qu2wZbmFPZQW/wAKAOcorrF8GpgF71yR/dQD+tTL4Qsx1uJz+Q/pQBxtFdmfCFl2uJx+K/4VE/gyE/cvJF+qg0AcjRXSy+DrgZ8q6ib2ZSv+NUZ/DmqQZIgEgHeNgf04NAGRRUk0E1u22aJ4z6OpFR0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUVr6d4fu7/Ekg8mE/wATDlh7CgDIAJIAGSegFbFl4bv7vDPGIIz/ABSDB/Bev8q6uw0a009QYYgZe8j8sfx7fhWnQBgWnhWxtwDNvuG/2zhfyFbMVvFAu2GJYx6KoFTUUAFFFFABRRRQAUUUUAFFFFAEciJIhV1VlPZhkVlXfhvTrnJEJhc/xRHb+nStmigDh73wreW+XtmFwg7D5W/Loaw5I3idkkRkdeqsMEfhXqlU7uwtr+Ly7mFXGOCwwR9D1FAHmtFdDqXhae3JksmM0fXYfvD6etc+VZWKsCpBwQRgg0AJRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFS21tNdzCGCNnkboB/M+gqxp2m3Gp3HlwrhR95z91R/j7V3WnabbabD5cCjLfeZvvMfegDN0vw3DZ7ZbnE045Ax8qn2Hc+5roaKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKytT0W11JS7DZMB8sqjn8fUVq0UAeaX+nXOnTbJk4P3XX7rfQ/0qpXp9zbQ3cLQzoHjbqprh9Z0OXTWMke6S2Y8N3X2b/GgDIooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAq9pmmTajc+XH8sa8uxHCj/H2qGys5dQukghHzNyWPRR3Jr0KwsodOtVghHyjkserHuTQAtpZwWMCwQLtRfXqT6k9zVuiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKjkjSVCkihlYYKsMg1JRQBwWt6K1hIZ4VJtmP1KH0Pt6GsavUZYkmjaORAyMMMp6EVwOs6S+mXAKgm3c5Rj2/2T70AZlFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABSqrOyoqksxwAOpNJXR+GNN8yU30y5VDiMHu3dvwoA29E0pdMtRuAM8gDSN6f7I9hWxRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVTvbOK/tXt5hlWHXup7EVcooA8xvLSWxupLeYYZT17MOxFV67fxHpf22z+0Rr+/hB6dWXuP61xFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAE9naveXcVtH96RsZ9B3P4CvSLaBLW3jgjGERQAK5nwlYbVkvnHJ+RM+33j/T8K62gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAA155run/YdSbYuIZfnT29R+Br0OsfxFY/bNKfaoMkP7xPw6/pQBwNFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAU5FZ3CKMsxAUepNNrX8N2v2jWoieVhBkP4cD9TQB2dhbLaWUNuOkahSfU9/1q5RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABSHkUtFAHm+rWf2LVJ4AMKG3L/unkf4VRrqvGNrzb3QHrGx/Uf1rlaACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigArrfB9vtguLgjlmCKfYDP8AWuSrvvDkPk6JBgYZ8uR9T/higDYooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAyfEFuLjRbgAAlF8xf+A8/wAs15/XqMqiWNkPRlKn8RXl7qUdkPVSVP4cUAJRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAh4BNem2EYi062QfwxqP0FeaAbmC+pxXqSDaij2FAD6KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACvNNVj8rVrtAMAStj6ZzXpdee+IU269dD1Kn81BoAy6KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAHxf6xP94fzr1MdK8qU7XVvQg16kh3Ip9QKAH0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFcB4m/5D8/0X/0EV39efeIm369cn0Kj8lFAGVRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAh5BFem2T+bY27j+KNW/QV5nXf+HZfN0W3yclQUP4E4/TFAGvRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAV5tq7+ZrF2/UGVgPoOK9Fd1RGc9FBJ/CvL5HMkruerMW/M5oAbRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAV13hCfda3FueSjhgPYj/ABFcjWx4aufI1mNCQFlUxn69R+ooA76iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigDL124+z6NcuDgsuxfq3H9a89rrPF91iOC1U8sxkYew4H6k/lXJ0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABT43eKVZEOGVgyn3BzTKKAPTbSdLu0iuEGFdQwqzXLeEr7dDLYueUO9P909f1/nXU0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUVl65ffYdLlkVgJHGxPqe/wCAyfwoA47W7v7Zq08gOUU7E+g4/nms6iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKALFjePY3sVxH/C2SPUdx+VekQzJcQpLGQyOoZT6g15fXU+FtUxmwmbg5aIn9V/r+dAHW0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABXBeJdR+2akY42zFBlRjoW/iP9Pwrote1RdPsWWNgLiUFU9VHdvw/nXCUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFOR3ikV42KupDKw6gim0UAeg6RqiapaB+BKvyuo7H1+hrVrzTT7+XT7tZozkdHTPDL6V6BZ3cV7bLPCwMbD8Qe4PvQBbooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAqG5uI7S3eeZtsaDJNPZgqlmIAAySegrhde1k6jN5MTf6LGeMfxt/e+npQBQ1G+fUbx53BAPCL/AHV7CqtFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVo6Rq0ul3GRloGPzp6+496zqKAPULa5iu4FnhcNGwyCKmrznStXn0ybKfNEx+eMnhvcehrurO+g1C3Etu4Kngg9VPoRQBcooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKYSFBJwB1NNlkSGNnkdVRRlmY4AFcXrPiB71TbWxZbfozdC/+A9qAH+INf+1brS0b9wDh3H8fsPb+dc/RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVYtLy4sZhNbuVYcEdmHoR3qvRQB3ela/b6iAkhEU/909G/wB0/wBOtbdeUjg5HWtzTfE1zahY7nM8Q4yT8yj69/xoA7qiqNlqVrqC7raZWOMlTwy/UVeoAKKKKACiiigAooooAKKKKACiiigAooooAKKKhnuYbWIyTyLGg/iY4FAE1UNR1S202PfO/wAx+6i8s30FYOo+Ks5jsEwennOP5D/H8q5iWWSeVpJXZ3Y5LMck0AX9U1e41OTDHZCDlYlPH1PqazqKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAHI7xuHjdlZeQynBH41tWXie8t2C3AFwg7sdrfn3/GsOigDvbTxJp91hTKYXP8ADKNv69K1UZXUMrBgehU5FeW1LBdXFs2YZpIj/ssRQB6jRXBQeJ9ShwGkSUDs6f1GKvxeMXAAmslPukmP0IoA66iubi8X2bffgnX8j/Wph4t049px9Y//AK9AG9RWCfFmnD/nsfpH/wDXpj+L7AD5Irhv+Agf1oA6GiuTfxioX93Zsx9XcD+QqlP4s1GQ4jWKIf7I3H9aAO5zWbda3p9nkS3Klh/CvzN+QrhLjUb27yJ7mV1P8JbA/IcVWoA6W98WyyEpZQ+WP78nJ/Lp/Oufubqe7k8y4laVvVjnH09KiooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACijvgdauQaVf3ODFaykf3iu0fmaAKdFb0PhS9fBlkiiHpksf0/xq/F4Stlx51zK59FAUf1oA5KjIHU4ru4vD2mRf8u28+ruTVyKws4f9Xawr9EFAHnSo7fdRm/3VJqZLC8f7lrM30Q16MFC/dAX6DFLk+tAHny6NqTdLKYfVcfzqQaBqh6Wjfiyj+td7RQBwY8Par/z6n/vtf8AGg+HtVH/AC6N/wB9r/jXeUUAcCdC1Retm/4EH+tRNpOoL1sp/wAEJr0OigDzV7a4j+/BKv1Q1EflODwfQ8V6fk+ppjwxSDDxIw/2kBoA8zor0GXRtNm+9ZxA+qjb/KqUvhbT3z5ZliP+y2R+RoA4uiulm8IOMmC7VvQOmP1FZ0/h7U4Mn7P5ijvGwb9OtAGXRT5I3ibbIjI3oykH9aZQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRWhZaJf3uGjhKRn+OT5R/iaAM+nxxvK4WNGdj/Cq5NdZaeFbaLDXMjTN/dX5V/xNbcFvDbJshiSMeirigDjrbwzqE+DIqwKe7nn8hWxbeFbOPBnkkmb0ztX9Of1reooAr29ja2o/cW8UeO4Xn8+tWKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAGyRpKpWRFcHsygj9ay7nw5p0+SImiY942x+h4rWooA5G58J3CZa2nSUf3W+Vv8KxrmxurNsXEDx+5HB/HpXo9IVDKVIDKeoIyDQB5jRXc3fh2wussqGFz/ABR8D8ulYF74ZvbfLQ7bhP8AZ4b8v8KAMWilZWRirqysOqsMEUlABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRWtp3h+7vsO48mE/xMOT9BQBkgEkADJPAArYsPDd5d4eUfZ4j3cfMfov8AjXUWGj2enAGKPdL3kflvw9Pwq/QBm2Wh2NiQyx+ZIP45PmP4DoK0qKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAK13p9rfLtuYVc9m6MPoetc5feFZUJeyk8wdfLfhvwPQ11lFAHmcsMkEhjmRkcdVYYNMr0e6s7a9i2XMSuvYkcj6HqK5nUfC00JMlkxlTrsb7w+nrQBz1FK6MjsjqVZeCrDBFJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRShSzBQCWJwABkmgBKtWWnXOoPshjyo+87cKv1NbWl+GGkxNf5VeohB+Y/wC8e30rqIokgjEcSKiLwFUYAoAy9N8PWtjteQCacfxMOFPsK16KKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCjf6RaaiuJkxIB8si8MPx7/jXJalol1p7F8ebB/z0UdP94dq7ugjIweRQB5hRXX6p4aiuCZbICKTqUPCt9PQ/pXKTwS28ximRkkXqpFAEdFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFaukaHNqTCRsx24PL45b2X/GgClZ2VxqEwit03H+Jjwqj1JrtNL0S205Q+PMnxzIw6f7o7VdtbWCyhEMKBEHp1J9Se5qagAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKqX+m22ow7J0yw+668Mv0P9Kt0UAcBqekXGmP843wk4WRRwfY+hrPr02SNJYykiKyMMMrDIIrkdY8PPa7rizBeHqydWX6eooAwKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACigDJwOTXVaJ4fEZW6vUy/VIj0X3b39qAK2jeH2nZbi9UrF1SM8Fvc+g/nXWqqooVVChRgADAApaKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigDnNa8PiYtc2SASdWiHAb3X0PtXKEFWIIIIOCD1FenVia3oSXytcW4C3IHI6B/r7+9AHF0U50eN2R1KspwysMEGm0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABQASQACSeABQBk4HWuv0HQxaqt3dJ+/PKqf4Pc+/8AKgA0LQRa7bq7XM55VD/B7n3/AJV0FFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAGPrWipqSGaEKt0o4PQOPQ/0NcU6PG7JIpVlOGUjBBr02sXXdEW/jM8ChblR9N49D7+lAHFUUpVkYqQVYHBBHINJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRXQeH9Fa4YXlwn7lT8in+I+p9h+tAFnw/oe0LfXS/MeYkYfd9z7+ldNRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAHP+IdE+0K15bL++UZdR/EPUe/865CvT65DxFpHks17bJiNj+8Ufwn1+hoA5+iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooqxY2ct/dpbxD5m5LdlHcmgC7omktqVzukBFvGfnP94/3RXcKiooRVCqowAOgFRWlrFZ2yW8Iwij8Se5PvU9ABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABSMiurIyhlYYKnoRS0UAcHrOlNp1z8gJgkJKN6f7J9xWZXo99Zx39o9vKPlbo3dT2Irz66tpLO5kt5lw6HB9D6Ee1AENFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAKFLMFAJJOAB1JrutE0tdOtMuB9okwXPp6L+H86yPDGlb2+3zL8qnEQPc92/DtXV0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVi+I9M+12v2iNczwjOB/Evcfh1raooA8worZ8Q6Z9ivPOiXEExJAHRW7j+tY1ABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVc0yyfUb1IBkL952/ur3qmOa7vQtN/s+xG9cTy4Z/b0X8KANKONIYljjUKigKqjsBTqKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAK1/ZJf2Ulu/AYfK391uxrzyaF4JnhkXDoxVh716ZXMeKdO4W/jX0WXH6N/T8qAOXooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoop8cbyyrHGpZ2YKoHcmgDY8N6b9rvftMi5ihIIz0Zuw/Dr+VdpVXTrJLCxjt1wSoyzf3mPU1aoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACo54UuIJIZBuR1KsPY1JRQB5veWr2V3JbSfeRsZ9R2P5VBXV+K7HfFHfIvzL8j49Ox/Pj8a5SgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACuj8Laf5kz3si/LH8qZ7t3P4D+dc/FG80qRxrudmCqPUmvRLK1Sys47ZOiLgn1Pc/nQBYooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCOeBLi3kgkGUdSp/GvObiFre4khcYaNip/CvSq5PxXZbLiK8UfLINjf7w6fp/KgDnKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiigAkgAZJ4AFAHQ+FbLzbp7tx8sPyrn+8f8B/OuuqnpdmLDTooMfMBuc+rHr/AJ9quUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFUtVs/tumzQgZYruX/eHI/wA+9XaKAPMOnXiitHW7T7Hq0yKMIx3r9D/9fNZ1ABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABWt4ds/teqozDMcI8xvr2H5/wAqya7XwzZ/Z9MExGHnbd/wEcD+p/GgDaooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAOc8W2u63gulHzIxRvoeR+v8AOuTr0TU7b7Zps8GMllJX/eHI/lXndABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAEtrA11dRW6/ekcL/jXpCIscaogwqqFUewrkfClr5t9JckfLCuF/wB5v/rZrsKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK871S3+yapcQgYCuSv0PI/nXolch4sgCX0VwBxIu0n/aX/wCsRQBz9FFFABRRRQAUUUUAf//Z"
            };

            return requestHashed;
        }

        public bool SaveUser(User request)
        {
            return _davxeShopDboHelper.SaveUser(request);
        }

        public string GenerateToken(string email)
        {
            var userId = GetUserIdByEmail(email);

            var claims = new[]
            {
                new Claim(ClaimTypes.Email, email),
                new Claim("userId", userId.ToString())
            };

            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_secretKey));
            var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

            var token = new JwtSecurityToken(
            issuer: "DavxeShop",
            claims: claims,
            expires: DateTime.Now.AddHours(1),
            signingCredentials: credentials
        );

            var tokenHandler = new JwtSecurityTokenHandler();

            return tokenHandler.WriteToken(token);
        }

        public bool CorrectUser(LogInRequest request)
        {
            if (!BCrypt.Net.BCrypt.Verify(request.Password, _davxeShopDboHelper.GetUserPasswordByEmail(request.Email)))
            {
                return false;
            }
            return true;
        }

        public bool StoreSession(string token, int userId)
        {
            if (userId == 0)
            {
                return false;
            }

            var session = new Session
            {
                UserId = userId,
                Token = token,
                Started = DateTime.Now,
                Ended = null
            };

            return _davxeShopDboHelper.StoreSession(session);
        }

        public bool LogOut(string token)
        {
            return _davxeShopDboHelper.LogOut(token);
        }

        public int? GetUserIdByEmail(string email)
        {
            return _davxeShopDboHelper.GetUserId(email);
        }

        public bool SendRecoveryCode(string email)
        {
            var user = _davxeShopDboHelper.GetUserByEmail(email);

            if (user == null) return false;

            string code = GenerateRecoveryCode(6);

            string message = $"<h3>Recuperación de contraseña</h3><p>Tu código de recuperación es: <strong>{code}</strong></p>";

            _emailService.SendEmail(email, "Código de recuperación", message);

            return _davxeShopDboHelper.SaveRecoveryCode(user.UserId, code, email);
        }

        public bool VerifyRecoveryCode(VerifyRecoverPasswordRequest request)
        {
            return _davxeShopDboHelper.VerifyRecoveryCode(request);
        }

        public bool ResetPassword(ResetPasswordRequest request)
        {
            var passwordHashed = new ResetPasswordRequest
            {
                Email = request.Email,
                Password = BCrypt.Net.BCrypt.HashPassword(request.Password, BCrypt.Net.BCrypt.GenerateSalt(5))
            };

            return _davxeShopDboHelper.ResetPassword(passwordHashed);
        }

        private string GenerateRecoveryCode(int length)
        {
            return new string(Enumerable.Repeat("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", length).Select(s => s[new Random().Next(s.Length)]).ToArray());
        }
    }
}
